version: "3.4"

services:
  bot:
    container_name: "go-vulnerability-informer"
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    volumes:
      - ../data/:/app/data
    ports:
      - "8080:8080"
    env_file:
      - ../.env